fix logic; reduce logging

diff --git a/xmScripts/xmlatex b/xmScripts/xmlatex
--- a/xmScripts/xmlatex
+++ b/xmScripts/xmlatex
@@ -325,6 +325,24 @@ reset_file_times() {
 
 
 
+xake_findKey() {
+    debug "Entering xake_findKey"
+
+    # If GPG_KEY_ID (and presumably GPG_KEY) are given, e.g. as Codespace/Action secrets 
+    # then ignore XM_KEYFILE (which probably should only be used for the DUMMY key ...)
+    if [[ -z "$GPG_KEY_ID" ]]
+    then
+        if [[ -f "$XM_KEYFILE" ]]
+        then
+            echo "Using settings from $XM_KEYFILE"
+            source $XM_KEYFILE
+	        echo "Using key_id $GPG_KEY_ID (with key ${GPG_KEY:0:5}...)"
+        fi
+        # [[ -z "$GPG_KEY_ID" ]]  &&  echo "WARNING: No GPG_KEY_ID set." 
+    fi
+
+}
+
 xake_name() {
     # TODO: migrate to lua ...?
     debug "Entering xake_name"
@@ -355,20 +373,7 @@ xake_name() {
         git remote -v
     fi
 
-    debug "Setting up gpg stuff ..."
-
-    # If GPG_KEY_ID (and presumably GPG_KEY) are given, e.g. as Codespace/Action secrets 
-    # then ignore XM_KEYFILE (which probably should only be used for the DUMMY key ...)
-    if [[ -z "$GPG_KEY_ID" ]]
-    then
-        if [[ -f "$XM_KEYFILE" ]]
-        then
-            echo "Using settings from $XM_KEYFILE"
-            source $XM_KEYFILE
-	        echo "Using key_id $GPG_KEY_ID (with key ${GPG_KEY:0:5}...)"
-        fi
-        [[ -z "$GPG_KEY_ID" ]]  &&  error "No GPG_KEY_ID set; serving will not be possible."     # still no key ...
-    fi
+    [[ -z "$GPG_KEY_ID" ]] && xake_genKey 
 
     debug "Loading GPG private key (inside container)"
     if [[ -f "$GPG_KEY" ]]
@@ -507,6 +512,19 @@ xake_name() {
 
 xake_genKey() {
 
+    # If GPG_KEY_ID (and presumably GPG_KEY) are given, e.g. as Codespace/Action secrets 
+    # then ignore XM_KEYFILE (which probably should only be used for the DUMMY key ...)
+    if [[ -z "$GPG_KEY_ID" ]]
+    then
+        if [[ -f "$XM_KEYFILE" ]]
+        then
+            echo "Using settings from $XM_KEYFILE"
+            source $XM_KEYFILE
+	        echo "Using key_id $GPG_KEY_ID (with key ${GPG_KEY:0:5}...)"
+            return    # Key found, no need to generate one
+        fi
+    fi
+
     [[ -z "$YOUR_EMAIL" && -n "$1" ]] && YOUR_EMAIL="$1"
     [[ -z "$YOUR_NAME" && -n "$2" ]] && YOUR_NAME="$*"
 
@@ -521,12 +539,12 @@ xake_genKey() {
 
     KEY_UID="$YOUR_NAME <$YOUR_EMAIL>"
 
-    echo "Starting generation of GPG key" 
+    [[ -z "$GPG_KEY_ID" ]]  &&  echo "No GPG_KEY_ID found: I'll generate a key for $KEY_UID" 
 
     if [[ -f .keyconfig ]] then
         echo "WARNING: Using existing .keyconfig" 
     else
-        echo "Creating keyconfig for $KEY_UID" 
+        debug "Creating keyconfig for $KEY_UID" 
         cat >.keyconfig <<EOF
 %no-protection
 Key-Type: RSA
@@ -540,37 +558,32 @@ EOF
     fi
 
     # Generate the key non-interactively
-    echo "" | gpg --batch --passphrase '' --gen-key .keyconfig || error "Could not create a new private key" 
+    echo "" | gpg --batch --passphrase '' --gen-key .keyconfig >.keyconfig.log 2>&1  || error "Could not create a new private key" 
 
     mv .keyconfig .keyconfig.bak || rm -f .keyconfig
 
     # Retrieve the fingerprint
     # FINGERPRINT=$(gpg --with-colons --list-keys "$YOUR_EMAIL" | grep '^fpr' | cut -d':' -f10)
-    FINGERPRINT=$(gpg --fingerprint "$YOUR_EMAIL" | grep -A1 pub | tail -n1 | tr -d ' ')
+    FINGERPRINT=$(gpg --fingerprint "$YOUR_EMAIL" 2>>.keyconfig.log | grep -A1 pub | tail -n1 | tr -d ' ')
 
     [[ -z "$FINGERPRINT" ]] && error "Could not retreive FINGERPRINT for generated key"
   
     # Output the fingerprint
-    echo "Key generated successfully!"
-    echo "Fingerprint: $FINGERPRINT"
+    echo "New key generated, with fingerprint: $FINGERPRINT"
 
-    PKEY=$(gpg --export-secret-subkeys -a "$YOUR_EMAIL" | base64 )
-    echo -e "Private key (base64 encoded):\n\nGPG_KEY=\"\n$PKEY\n\"\n\n"
+    PKEY=$(gpg --export-secret-subkeys -a "$YOUR_EMAIL" 2>> .keyconfig.log | base64 )
 
     IS_XMKEYFILE_IGNORED=$(git check-ignore -v .xmKeyFile)
 
     if [[ -z "$IS_XMKEYFILE_IGNORED" ]]
     then
+        echo -e "Private key (base64 encoded):\n\nGPG_KEY=\"\n$PKEY\n\"\n\n"
         echo "You do NOT have a rule to gitignore a .xmKeyFile. I won't create one until you add a line '.XmKeyFile*' to your .gitignore file."
         echo "Note: you don't have to use a .xmKeyFile, eg when using 'secrets' in Codespaces or Actions."
-    elif [[ -f .xmKeyFile ]] then
+    elif [[ -f .xmKeyFile ]] then   # DOES NOT HAPPEN ANYMORE ???
         echo "You already have a .xmKeyFile which I DID NOT overwrite."
         echo "Remove the existing file and rerun 'xmlatex genKey' if you want to store a new key in .xmKeyFile"
     else
-        echo "I create a .xmKeyFile for a newly generated key for $KEY_UID."
-        echo "This is convenient for quick testing, or in some cases while developing on your local PC."
-        echo "*** Do NEVER publish this key (eg by commit/push) ***"
-
         cat >.xmKeyFile <<EOF
 #
 # This file contains a private GPG key for $KEY_UID to publish Ximera courses.
@@ -584,27 +597,30 @@ GPG_KEY="\\
 $PKEY
 "
 EOF
+        echo "I created a .xmKeyFile with a newly generated key for $KEY_UID."
+        echo "This is convenient for quick testing, or in some cases while developing on your local PC."
+        # echo "*** Do NEVER publish this key (eg by commit/push) ***"
     fi
 
 
     # gpg --batch --yes --delete-secret-key "$FINGERPRINT"
     # gpg --batch --yes --delete-key "$FINGERPRINT"
 
- if [[ "$YOUR_EMAIL" == *dummy* || "$YOUR_EMAIL" == *here*your* ]]
- then
-    echo "This is a dummy key $KEY_UID (thus: only for testing/local development)."
- else
-    echo "If you want to use this key $KEY_UID for offical publication of a Ximera courses, please SAVE it in a SAFE location."
-    echo "This could be as 'Secrets' under your personal 'Settings -> Codespaces' in Github."
-    echo "           or as 'Secrets' under your personal 'Settings -> Actions' in Github."
-    echo "           or in a .xmKeyFile file on your PC or in a Codespace."
-    echo "There are TWO 'secrets' to be saved:"
-    echo "   GPG_KEY_ID  with value $FINGERPRINT"
-    echo '   GPG_KEY     with value the private key that was printed above, between the  GPG_KEY=" and " lines'
-    echo ""
-    echo "If you only want to test something on a local ximeraServer it's most convenient to use a temporary .xmKeyFile,"
-    echo "   and generate a new key next time."
-fi
+    if [[ "$YOUR_EMAIL" == *dummy* || "$YOUR_EMAIL" == *DUMMY* || "$YOUR_EMAIL" == *here*your* ]]
+    then
+       echo "This is a dummy key $KEY_UID (thus: only for testing/local development)."
+    else
+       echo "If you want to use this key $KEY_UID for offical publication of a Ximera courses, please SAVE it in a SAFE location."
+       echo "This could be as 'Secrets' under your personal 'Settings -> Codespaces' in Github."
+       echo "           or as 'Secrets' under your personal 'Settings -> Actions' in Github."
+       echo "           or in a .xmKeyFile file on your PC or in a Codespace."
+       echo "There are TWO 'secrets' to be saved:"
+       echo "   GPG_KEY_ID  with value $FINGERPRINT"
+       echo '   GPG_KEY     with value the private key that was printed above, between the  GPG_KEY=" and " lines'
+       echo ""
+       echo "If you only want to test something on a local ximeraServer it's most convenient to use a temporary .xmKeyFile,"
+       echo "   and generate a new key next time."
+    fi
 
 }
 
@@ -811,7 +827,8 @@ then
     
     # Unfortunately, 'name' and 'genKey' can not (yet?) be integrated into luaxake ...
 
-    [[ -z "$GPG_KEY_ID" ]] && xake_genKey  # If no key present, try genKey (which might find and set one, or generate a new one)
+    [[ -z "$GPG_KEY_ID" ]] && xake_findKey  # If no key present, try to find and set one
+    [[ -z "$GPG_KEY_ID" ]] && xake_genKey   # If still no key present, try genKey to generate one)
     
     # git remote show ximera >/dev/null 2>&1 || xake_name
     xake_name    # set the name (should only be needed if not-yet-set, OR CHANGED)
